---
title             : "Table28"
shorttitle        : ""

author: 
  - name          : "Adam Garber"

number_sections: no

documentclass     : "apa6"
classoption       : "doc"
output            : papaja::apa6_word
fig_width: 6
fig_height: 4
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "left",
	message = FALSE,
	warning = FALSE,
	out.width = "80%"
)

library("papaja")
library(knitr)
library(janitor)
#library(ggpubr)
#library(psych)
library(tidyverse)
library(apaTables)
library(patchwork)
library(MplusAutomation)
library(here)
library(gt)
library(officer)
```

------------------------------------------------------------------------

Read simulation summary output files for each sample size condition

NOTE: The 9 output files were copied to folder `C1_Outputs` for accessibility
```{r}
lca_sim <- readModels(here("C1_Outputs"), what = "parameters")

lcaNames <- names(lca_sim)
unstandardizedlca <- sapply(sapply(lca_sim, "[", "parameters"), "[", "unstandardized")
names(unstandardizedlca) <- lcaNames

```

```{r}
apply_table_setup <- function(data) {
  table_setup <- data %>%
    rename(Power = pct_sig_coef,
           Parameter = param,
           Coverage = cover_95)  %>% 
    select(Parameter:LatentClass)
  
  return(table_setup)
}

resultslca <- lapply(unstandardizedlca, apply_table_setup)

lca_combined <- do.call("rbind", resultslca) %>% 
  as.data.frame() %>% 
  mutate(Parameter = factor(Parameter)) %>% 
  purrr::modify_if(is.character, as.numeric) %>% 
  mutate(Condition = as.array(rep(1:9, each = 89))) %>% 
  mutate(Condition = factor(Condition,
          labels = c(`1` = "N=500", `2` = "N=1000", `3` = "N=1500", `4`= "N=2000",
                     `5` = "N=2500",`6` = "N=3000",`7` = "N=4000",`8` = "N=5000", `9` = "N=6000")))

```

Calculate results: Group by condition (NOTE: Values are averaged across model parameters)
```{r}
fit_by_cond <- lca_combined %>% 
  group_by(Condition) %>% 
  summarize(
    avg_Bias = mean(abs(average-population)/abs(population))*100,
    max_Bias = max(abs(average-population)/abs(population))*100,
    avg_SE_Bias = mean(abs(average_se-population_sd)/population_sd)*100,
    max_SE_Bias = max(abs(average_se-population_sd)/population_sd)*100,
    avg_Coverage = mean(Coverage),
    avg_Power = mean(Power)
  ) %>% 
  adorn_rounding(digits = 3)

```

------------------------------------------------------------------------

Table 28
```{r}

apa_table(
  fit_by_cond,
  caption = ""
  #align = c("l", "r", "r", "r", "r", "r", "r", "r")
)

```

------------------------------------------------------------------------

Table 29

------------------------------------------------------------------------

Extract fit data
```{r}

output_lca <- readModels(here("C2-Split-Sample"), filefilter = "explr", quiet = TRUE)

enum_extract <- LatexSummaryTable(output_lca,
    keepCols = c("Title","Parameters","LL","BIC","aBIC",
    "BLRT_PValue","T11_VLMR_PValue","Observations"),
    sortBy = "Title") 

allFit <- enum_extract %>%
  mutate(CAIC = -2 * LL + Parameters * (log(Observations) + 1)) %>%
  mutate(AWE = -2 * LL + 2 * Parameters * (log(Observations) + 1.5)) %>%
  mutate(SIC = -.5 * BIC) %>%
  mutate(expSIC = exp(SIC - max(SIC))) %>%
  mutate(BF = exp(SIC - lead(SIC))) %>%
  mutate(cmPk = expSIC / sum(expSIC)) %>%
  dplyr::select(1:5, 9:10, 6:7, 13, 14) %>%
  arrange(Parameters)
```

Create table
```{r}
fit_table <- allFit %>%
  gt() %>%
  tab_header(title = md("**Model Fit Summary Table**")) %>%
  cols_label(
    Title = "Classes",
    Parameters = md("Par"),
    LL = md("*LL*"),
    T11_VLMR_PValue = "VLMR",
    BLRT_PValue = "BLRT",
    BF = md("BF"),
    cmPk = md("*cmPk*")
  ) %>%
  tab_footnote(
    footnote = md(
      "*Note.* Par = Parameters; *LL* = model log likelihood;
BIC = Bayesian information criterion;
aBIC = sample size adjusted BIC; CAIC = consistent Akaike information criterion;
AWE = approximate weight of evidence criterion;
BLRT = bootstrapped likelihood ratio test p-value;
VLMR = Vuong-Lo-Mendell-Rubin adjusted likelihood ratio test p-value;
*cmPk* = approximate correct model probability."
    ),
locations = cells_title()
  ) %>%
  tab_options(column_labels.font.weight = "bold") %>%
  fmt_number(c(3:7),
             decimals = 2) %>%
  sub_missing(1:11,
              missing_text = "--") %>%
  fmt(c(8:9, 11),
  fns = function(x)
  ifelse(x < 0.001, "<.001", scales::number(x, accuracy = .01))
  ) %>%
  fmt(10,fns = function (x)
      ifelse(x > 100, ">100", scales::number(x, accuracy = .01))
  ) %>%  
  tab_style(
    style = list(
      cell_text(weight = "bold")),
    locations = list(cells_body(
     columns = BIC,
     row = BIC == min(BIC[c(1:3)]) # Change this to the number of classes you are evaluating
    ),
    cells_body(
     columns = aBIC,
     row = aBIC == min(aBIC[1:3])
    ),
    cells_body(
     columns = CAIC,
     row = CAIC == min(CAIC[1:3])
    ),
    cells_body(
     columns = AWE,
     row = AWE == min(AWE[1:3])
    ),
    cells_body(
     columns = cmPk,
     row =  cmPk == max(cmPk[1:3])
     ),    
    cells_body(
     columns = BF,
     row =  BF > 10),
    cells_body( 
     columns =  T11_VLMR_PValue,
     row =  ifelse(T11_VLMR_PValue < .05 & lead(T11_VLMR_PValue) > .05, T11_VLMR_PValue < .05, NA)),
    cells_body(
     columns =  BLRT_PValue,
     row =  ifelse(BLRT_PValue < .05 & lead(BLRT_PValue) > .05, BLRT_PValue < .05, NA))
  )
)


```

```{r}

apa_table(
  allFit,
  caption = ""
  #align = c("l", "r", "r", "r", "r", "r", "r", "r")
)

```






